### ISSUE TITLE
We should store originally_captured_at or a total_time_spent field of some kind

### ISSUE THREAD

**Issue by rradonic** [learningtapestry/analytics#300]
The captured_at field for raw messages gets updated every time new raw messages come in from the importer, so we can't use (updated_at - captured_at) to get the total time spent on a page.

We also can't do (updated_at - created_at) since created_at stores the time that the raw message got imported into PostgreSQL which happens when the importer gets run, and not the time that the user started looking at the page.

captured at stores the time the user started looking at the site most recently, so if they look at the page for at 13:00 for 10 seconds we store 13:00, and if they move to another tab and go back to our tab at 13:04 for 10 more seconds and then close the tab, captured_at will say 13:04 and there's no more record of 13:00 anywhere, we're losing the original time the user started looking at the page.

**Comment by jwrubel** [comment]
This is a good idea. It looks like the `heartbeat_id` field was intended to be used for this? There's a discussion in [this issue](https://github.com/learningtapestry/analytics/issues/274). I'm not sure if the data makes sense based on what you're seeing but it looks like that was the original intent.

**Comment by jwrubel** [comment]
Is this still a valid issue now that we understand more about how time spent is stored?

**Comment by rradonic** [comment]
We're still missing the original time the user hit the page, but we do store total time spent so it's probably enough for now.
